spring.application.name=datn

#config mysql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/datn
spring.datasource.username=vutienthanh
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Khai báo Dialect cho PostgreSQL (Giúp Hibernate d?ch code Java sang câu l?nh SQL chu?n c?a Postgres)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Tùy ch?n thêm: Fomat SQL cho d? ??c trên console log
spring.jpa.properties.hibernate.format_sql=true

#jwt config
jwt.secret = r6BkNL75W4TBtFM9pxGJCwybBE96kLoF0gATvPzzvK/UE8Xb+0IJSyI1T94UDN5Z
jwt.expiration = 18000000
jwt.long.expiration = 86400000

# config redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000
spring.session.store-type=redis

# --- Google OAuth2 Configuration ---
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#config gmail
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = ${EMAIL_USERNAME}
spring.mail.password = ${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

#validation config
server.error.include-message=always
server.error.include-binding-errors=always

frontend.url=http://localhost:3000