spring.application.name=datn

#config mysql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/DATN
spring.datasource.username=vutienthanh
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Khai báo Dialect cho PostgreSQL (Giúp Hibernate d?ch code Java sang câu l?nh SQL chu?n c?a Postgres)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Tùy ch?n thêm: Fomat SQL cho d? ??c trên console log
spring.jpa.properties.hibernate.format_sql=true
