package com.example.demo.Enum;

import lombok.Getter;

@Getter
public enum ErrorCode {
    USER_NOT_FOUND(101, "User not found"),
    USER_AlREADY_EXISTED(102, "User have already existed"),
    USER_IS_DELETED(103, "User is deleted"),
    USER_AlREADY_ACTIVE(104, "User have already active"),
    ROLE_ALREADY_EXISTED(201, "Role have already existed"),
    UNAUTHORIZED_ACTION(105, "Unauthorize action"),
    ROLE_NOT_FOUND(202, " Role not found"),
    INVALID_OTP_CODE(9999, "Invalid otp code"),
    USER_NOT_ACTIVE(103, "User is not active"),
    PASSWORD_NOT_CORRECT(104, "Password is not correct"),
    OAUTH_ACCOUNT_PASSWORD_NOT_ALLOWED(107, "Google login account cannot use password features"),
    UNAUTHENTICATED(9998, "Unauthenticated"),
    EMAIL_OR_PASSWORD_NOT_CORRECT(105, "Email or password is not correct"),
    PASSWORD_NOT_MATCH(106, "Confirm password is not true"),
    BRAND_ALREADY_EXISTED(301, "Brand have already existed"),
    BRAND_NOT_FOUND(302, "Brand not found"),
    CATEGORY_NOT_FOUND(304, "Category not found"),
    CATEGORY_ALREADY_EXISTED(305, "Category have already existed"),
    INVALID_CATEGORY_PARENT(306, "Category cannot be its own parent"),
    CATEGORY_CYCLE_DETECTED(309, "Category cycle detected"),
    ATTRIBUTE_NOT_FOUND(307, "Attribute not found"),
    ATTRIBUTE_ALREADY_EXISTED(308, "Attribute have already existed"),
    INVALID_ATTRIBUTE_VALUE(310, "Invalid attribute value"),
    ATTRIBUTE_VALUE_NOT_FOUND(311, "Attribute value not found"),
    PRODUCT_NOT_FOUND(401, "Product not found"),
    ATTRIBUTE_NOT_ALLOWED_FOR_CATEGORY(312, "Attribute not allowed for category"),
    SKU_CODE_ALREADY_EXISTED(313, "Sku code already existed"),
    CART_NOT_FOUND(501, "Cart not found"),
    CART_ITEM_NOT_FOUND(502, "Cart item not found"),
    UNAUTHORIZED_CART_ACCESS(503, "You don't have permission to modify this cart item"),
    SKU_NOT_FOUND(504, "Product SKU not found"),
    SKU_INACTIVE(505, "Product SKU is no longer available"),
    INSUFFICIENT_STOCK(506, "Not enough stock available"),
    INVALID_QUANTITY(507, "Quantity must be greater than 0"),
    MISSING_CART_IDENTIFIER(508, "Must provide either UserId or SessionId"),
    ADDRESS_NOT_FOUND(509, "Address not found"),
    SHIPPING_METHOD_NOT_FOUND(510, "Shipping method not found"),
    COUPON_NOT_FOUND(511, "Coupon not found"),
    INVALID_DATE_RANGE(512, "Invalid date range"),
    COUPON_INACTIVE(513, "Coupon inactive"),
    COUPON_NOT_STARTED(514, "Coupon not started"),
    COUPON_EXPIRED(515, "Coupon expired"),
    COUPON_USAGE_EXCEEDED(516, "Coupon usage exceeded"),
    COUPON_NOT_APPLICABLE(517, "Coupon not applicable"),
    SHIPPING_METHOD_ALREADY_EXISTED(518, "Shipping method already existed"),
    COUPON_ALREADY_EXISTED(519, "Coupon already existed"),
    CART_IS_EMPTY(520, "Cart is empty"),
    PAYMENT_METHOD_NOT_FOUND(521, "Payment method not found"),
    PAYMENT_METHOD_ALREADY_EXISTED(522, "payment method have already existed"),
    OTP_RATE_LIMIT_EXCEEDED(523, "Otp rate limit exceeded"),
    OTP_EXPIRED(525, "Otp expired"),
    INVALID_REFRESH_TOKEN(526, "Invalid Token"),
    WISHLIST_ITEM_ALREADY_EXISTED(601, "Product already in wishlist"),
    WISHLIST_ITEM_NOT_FOUND(602, "Product not found in wishlist"),
    IMAGE_NOT_FOUND(701, "Image not found"),
    SLUG_ALREADY_EXISTED(402, "Slug already existed"),
    DUPLICATE_ATTRIBUTE_VALUE_IN_SPECS(403, "Duplicate attribute value in specs"),
    DUPLICATE_ATTRIBUTE_VALUE_ID_IN_REQUEST(404, "Duplicate attribute value id in request"),
    REVIEW_ALREADY_EXISTED(801, "Review already existed for this order item"),
    REVIEW_NOT_FOUND(802, "Review not found"),
    INVALID_INTERACTION_TYPE(901, "Invalid interaction type"),
    SELECTED_ITEMS_NOT_FOUND(902, "selected items not found" ),
    ORDER_NOT_FOUND(903,"Order not found" ),
    WALLET_NOT_FOUND(904, "Wallet not found"),
    WALLET_INACTIVE(905, "Wallet inactive"),
    INSUFFICIENT_WALLET_BALANCE(906, "Insufficient wallet balance"),
    INVALID_WALLET_AMOUNT(907, "Invalid wallet amount"),
    WALLET_TRANSACTION_NOT_FOUND(908, "Wallet transaction not found"),
    WALLET_TRANSACTION_ALREADY_PROCESSED(909, "Wallet transaction already processed"),
    ORDER_ALREADY_REFUNDED(910, "Order already refunded"),
    ORDER_NOT_PAID(911, "Order not paid"),
    INVALID_ORDER_STATUS(912, "Invalid order status"),
    BANNER_NOT_FOUND(913, "Banner not found"),
    ORDER_RETURN_NOT_FOUND(914, "Order return request not found"),
    ORDER_RETURN_ALREADY_EXISTED(915, "Order return request already existed"),
    ORDER_NOT_DELIVERED(916, "Order has not been delivered"),
    ORDER_RETURN_ALREADY_PROCESSED(917, "Order return request already processed"),
    ORDER_RETURN_EXPIRED(918, "Return request period has expired"),
    CHATBOT_SESSION_NOT_FOUND(919, "Chatbot session not found"),
    VALUE_MIN_ORDER_IS_NOT_GREATER_VALUE_MAX_ORDER(920, "Giá trị đơn hàng tối thiểu không được lớn hơn tối đa."),
    ATTRIBUTE_VALUE_ALREADY_EXISTED(921, "Attribute value already existed"),
    ATTRIBUTE_VALUE_IN_USE(922, "Attribute value is being used by product, product sku or product spec"),
    ATTRIBUTE_IN_USE(923, "Attribute is being used by product, product sku or product spec"),
    EMAIL_SEND_FAILED(924, "Cannot send OTP to this email address");

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    private final int code;
    private final String message;
}
